#!/bin/bash
SCRIPT_NAME=$(realpath $0)

DOCKER_DIR=$(dirname ${SCRIPT_NAME})
DOCKER_CMD=$(basename ${SCRIPT_NAME})

if [ ! -f $DOCKER_DIR/version ];then
    echo "Cannot find  version file"
    exit 1
    
fi
. $DOCKER_DIR/version

docker run -it --rm \
-u $(id $USER -u) \
-w /app \
-v $(pwd):/app \
-v "${HOME}/:${HOME}/" \
-v "${SSH_AUTH_SOCK}:/ssh-agent" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
-e "KOPS_STATE_STORE=${KOPS_STATE_STORE}" \
-e "CLUSTER_NAME=${CLUSTER_NAME}" \
-e "CLUSTER_ENV=${CLUSTER_ENV}" \
-e "AWS_PROFILE=${AWS_PROFILE}" \
kops:${APP_VERSION} $DOCKER_CMD $@
