#!/bin/bash
SCRIPT_NAME=$(realpath $0)

DOCKER_DIR=$(dirname ${SCRIPT_NAME})
DOCKER_CMD=$(basename ${SCRIPT_NAME})

. ${DOCKER_DIR}/version


#-u $(id $USER -u) \
docker run -it --rm \
-w /app \
-v $(pwd):/app \
--network=host \
-v "${HOME}/.aws:/${HOME}/.aws" \
-v "${HOME}/.ssh:/${HOME}/.ssh" \
-v "${HOME}/vaultpass:/tmp/vaultpass" \
-v "${SSH_AUTH_SOCK}:/ssh-agent" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
-e "AWS_PROFILE=${AWS_PROFILE}" \
-e "ANSIBLE_VAULT_PASSWORD_FILE=/tmp/vaultpass" \
-e "ANSIBLE_PRIVATE_KEY_FILE=${HOME}/.ssh/${ANSIBLE_KEY}" \
-e "ANSIBLE_HOST_KEY_CHECKING=False" \
--log-driver none \
${APP_NAME}:${APP_VERSION} $DOCKER_CMD $@
