#!/bin/bash
SCRIPT_NAME=$(realpath $0)

DOCKER_DIR=$(dirname ${SCRIPT_NAME})
DOCKER_CMD=$(basename ${SCRIPT_NAME})

. ${DOCKER_DIR}/version

docker run -it --rm \
-u $(id $USER -u) \
-w /app \
-v $(pwd):/app \
-v "${HOME}/.aws:/${HOME}/.aws" \
-v "${HOME}/.ssh:/${HOME}/.ssh" \
-v "${HOME}/vaultpass:/app/vaultpass" \
-v "${SSH_AUTH_SOCK}:/ssh-agent" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
-e "ANSIBLE_VAULT_PASSWORD_FILE=/app/vaultpass" \
-e "ANSIBLE_HOST_KEY_CHECKING=False" \
-e "AWS_PROFILE=${AWS_PROFILE}" \
--log-driver none \
${APP_NAME}:${APP_VERSION} $DOCKER_CMD $@
