#!/bin/bash
SCRIPT_NAME=$(realpath $0)

DOCKER_DIR=$(dirname ${SCRIPT_NAME})
DOCKER_CMD=$(basename ${SCRIPT_NAME})

if [ ! -f $DOCKER_DIR/version ];then
    echo "Cannot find version file"
    exit 1
fi
# get app info
. $DOCKER_DIR/version

#--dns 10.34.21.250 \
# map drives
docker run -it --rm \
-u $(id $USER -u) \
--network host \
-w /app \
-v $(pwd):/app \
-v "${HOME}/.aws:${HOME}/.aws" \
-v "${HOME}/.kube:${HOME}/.kube" \
-v "${HOME}/.ssh:${HOME}/.ssh" \
-v "${SSH_AUTH_SOCK}:/ssh-agent" \
-e "KUBECONFIG=$KUBECONFIG" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
-e "AWS_PROFILE=$AWS_PROFILE" \
$APP_NAME:${APP_VERSION} $DOCKER_CMD "$@"
