#!/bin/bash
DOCKER_DIR=$(dirname $0)
DOCKER_CMD=$(basename $0)
if [ ! -f $DOCKER_DIR/terraform_version ];then
    echo "Cannot find terraform version file"
    exit 1
    
fi
. $DOCKER_DIR/terraform_version


docker run -it --rm \
-u $(id $USER -u) \
-w /app \
-v $(pwd):/app \
-v "${HOME}/.aws:${HOME}/.aws" \
-v "${HOME}/.ssh:${HOME}/.ssh" \
-v "${HOME}/vaultpass:${HOME}/vaultpass" \
-v "${SSH_AUTH_SOCK}:/ssh-agent" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
-e "TF_LOG=${TF_DEBUG}" \
-e "TF_LOG_PATH=tf.log" \
terraform:${TERRAFORM_VERSION} $DOCKER_CMD $@
