#!/bin/bash
DOCKER_DIR=$(dirname $0)
DOCKER_CMD=$(basename $0)
if [ ! -f $DOCKER_DIR/version ];then
    echo "Cannot find version file"
    exit 1
    
fi

. $DOCKER_DIR/version

docker run -it --rm \
-u $(id $USER -u) \
-v $(pwd):/app \
-v "$DOCKER_DIR/settings:$HOME/.jira.d" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
--log-driver none \
${APP_NAME}:${APP_VERSION} "$@"
