#!/bin/bash  
SCRIPT_NAME=$(realpath $0)

DOCKER_DIR=$(dirname ${SCRIPT_NAME})
DOCKER_CMD=$(basename ${SCRIPT_NAME})
JENKINS=/home/jenkins
. ${DOCKER_DIR}/version

docker run -i --rm \
-u $(id $USER -u) \
-w /app \
-v $(pwd):/app \
-v "/tmp:/tmp" \
-v "${HOME}/.aws:${JENKINS}/.aws" \
-v "${HOME}/.ssh:/app/.ssh" \
-v "${SSH_AUTH_SOCK}:/ssh-agent" \
-v "${HOME}/.gitconfig:${JENKINS}/.gitconfig" \
-v "${HOME}/vaultpass:/app/vaultpass" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
-e "ANSIBLE_HOST_KEY_CHECKING=False" \
-e "ANSIBLE_ROLES_PATH=roles" \
-e "ANSIBLE_PRIVATE_KEY_FILE=/app/.ssh/ansible_private_key_file" \
-e "ANSIBLE_VAULT_PASSWORD_FILE=/app/vaultpass" \
--log-driver none \
${APP_NAME}:${APP_VERSION} $DOCKER_CMD $@
