#!/bin/bash
SCRIPT_NAME=$(realpath $0)

DOCKER_DIR=$(dirname ${SCRIPT_NAME})
DOCKER_CMD=$(basename ${SCRIPT_NAME})

. ${DOCKER_DIR}/version

docker run -it --rm \
-u $(id $USER -u) \
-w /app \
-v $(pwd):/app \
-v "${HOME}/.aws:${HOME}/.aws" \
-v "${HOME}/.ssh:${HOME}/.ssh" \
-v "${HOME}/vaultpass:${HOME}/vaultpass" \
-v "${SSH_AUTH_SOCK}:/ssh-agent" \
-e "SSH_AUTH_SOCK=/ssh-agent" \
-e "ANSIBLE_HOST_KEY_CHECKING=False" \
-e "ANSIBLE_PRIVATE_KEY_FILE=${HOME}/.ssh/ansible_private_key_file" \
-e "ANSIBLE_VAULT_PASSWORD_FILE=${HOME}/vaultpass" \
--log-driver none \
${APP_NAME}:${APP_VERSION} $DOCKER_CMD "$@"
